### ISSUE TITLE
multiDexEnabled=true时 hash文件生成没有内容

### ISSUE THREAD

**Issue by RebortY** [jasonross/NuwaGradle#9]

**Comment by zmc0218** [comment]
@yanglinglong1    请问您提的这个问题后来是怎么解决的啊？

**Comment by RebortY** [comment]
@zmc0218 后来我发现，在gradle tools 版本在 1.3.1 的时候， dexDebug 过程会处理class文件， 如果我不控制nuwa配置中的include参数的话，就会把 allclass.jar 里面的所有class 包括第三方的都处理了， 只有处理了第三方的class时就会出现异常，所以我 将 Include指定了只有自己的项目包， 就没有问题了。 不过为什么处理第三方class gradle 的 dexDebug任务会报错，具体原因还是不清楚

**Comment by zmc0218** [comment]
@yanglinglong1  我使用的gradle版本也是1.3.1  build文件中也添加了
nuwa{
    includePackage = ['cn/yoho']
}

代码修改后使用  gradle clean nuwaBaidu_1_2931releasePatch -P NuwaDir=D:\nuwa

还是只有空的patch文件夹

**Comment by RebortY** [comment]
@zmc0218 nuwa目录后面要加上 /  因为 读取的时候，是  nuwa/debug/ 这样的目录， 如果你输入参数后面没有 / 就匹配不上目录了
